# Para crear el environment e instalar los paquetes necesarios, una vez descargados los archivos, moverse al directorio y ejectuar:
#         conda env create
#         conda activate varios

# para actualizar (agregar/sacar/modificar versiones), modificar este archivo y despues ejecutar:
#         conda env update --prune

# para limpiar de paquetes instalados manualmente (pruebas), borrar el environment y volverlo a crear:
#         conda deactivate
#         conda env remove -n varios
#         conda env create
#         conda activate varios


name: varios
dependencies:
  - python  # con python=3.6, por ejemplo, especifico la version. Si no, usa la mas nueva disponible
  - numpy
  - pip
  - pip: # PyPI packages
    - pyenchant # diccionario, lo uso en combinaLetras
    - pycountry # para obtener las descripciones de los diccionarios

